== LogAdapter
The LogAdapter is used for logging. When a step or the executer has something to log it will use the
LogAdapter. The could be different implementation for a LogAdapter. This default implementation
just writes the log to the console output.


=== Methods
The log adapter has only one method.
The log method returns a promise.

[source, js]
----
logAdapter.log(logMessage) : promise
----


.Format of the logMessage
[source, js]
----
const logMessage = {
  meta:{
    run:{                       <1>
      start: <time>,
      id: 'id'
    },
    tc:{                        <2>
      id: 'id',
      name: 'great tc name'
    },
    step:{                      <3>
      id: 'id',
      name: 'great step name'
      typ: ('singel'| ''|)
    }
  }
  data:{},                      <4>
  logLevel: LEVEL_INFO          <5>
}
----
<1> The 'run' section of the meta block is always there. No log without a run. This is filled automatically.
<2> If the log comes from a test case or a step also the 'tc' section is provided. This is filled automatically.
<3> The 'step' section is only provided if the log was initiated by a step. This is filled automatically.
<4> The 'data' section contains the real message data.
<5> The logLevel is also set automatically.
